local textures = {
    [1]="tint_square",
    [2]="squared_bar_1",
    [3]="squared_bar_2",
    [4]="squared_bar_3",
    [5]="squared_bar_4",
    [6]="squared_bar_5",
    [7]="squared_bar_6",
    [8]="squared_vbar_1",
    [9]="squared_vbar_2",
    [10]="squared_vbar_3",
    [11]="squared_vbar_4",
    [12]="squared_vbar_5",
    [13]="squared_v_gradient",
    [14]="squared_v_gradient2",
    [15]="squared_h_gradient",
    [16]="squared_h_gradient2",
    [17]="squared_border_1",
    [18]="squared_diagonal_stripe",
    [19]="squared_checkered",
	[20]="SharedMediaAluminium",
	[21]="SharedMediaArmory",
	[22]="SharedMediaBantoBar",
	[23]="SharedMediaBars",
	[24]="SharedMediaBumps",
	[25]="SharedMediaButton",
	[26]="SharedMediaCharcoal",
	[27]="SharedMediaCilo",
	[28]="SharedMediaCloud",
	[29]="SharedMediacombo",
	[30]="SharedMediaComet",
	[31]="SharedMediaDabs",
	[32]="SharedMediaDarkBottom",
	[33]="SharedMediaDiagonal",
	[34]="SharedMediaEmpty",
	[35]="SharedMediaFalumn",
	[36]="SharedMediaFifths",
	[37]="SharedMediaFlat",
	[38]="SharedMediaFourths",
	[39]="SharedMediaFrost",
	[40]="SharedMediaGlamour",
	[41]="SharedMediaGlamour2",
	[42]="SharedMediaGlamour3",
	[43]="SharedMediaGlamour4",
	[44]="SharedMediaGlamour5",
	[45]="SharedMediaGlamour6",
	[46]="SharedMediaGlamour7",
	[47]="SharedMediaGlass",
	[48]="SharedMediaGlaze",
	[49]="SharedMediaGlaze2",
	[50]="SharedMediaGloss",
	[51]="SharedMediaGraphite",
	[52]="SharedMediaGrid",
	[53]="SharedMediaHatched",
	[54]="SharedMediaHealbot",
	[55]="SharedMediaLiteStep",
	[56]="SharedMediaLiteStepLite",
	[57]="SharedMediaLyfe",
	[58]="SharedMediaMelli",
	[59]="SharedMediaMelliDark",
	[60]="SharedMediaMelliDarkRough",
	[61]="SharedMediaMinimalist",
	[62]="SharedMediaOtravi",
	[63]="SharedMediaOutline",
	[64]="SharedMediaPerl",
	[65]="SharedMediaPerl2",
	[66]="SharedMediaPill",
	[67]="SharedMediaRain",
	[68]="SharedMediaRocks",
	[69]="SharedMediaRound",
	[70]="SharedMediaRuben",
	[71]="SharedMediaRunes",
	[72]="SharedMediaSkewed",
	[73]="SharedMediaSmooth",
	[74]="SharedMediaSmoothv2",
	[75]="SharedMediaSmudge",
	[76]="SharedMediaSteel",
	[77]="SharedMediaStriped",
	[78]="SharedMediaTube",
	[79]="SharedMediaWater",
	[80]="SharedMediaWglass",
	[81]="SharedMediaWisps",
	[82]="SharedMediaXeon",
    [83]="squared_tint",
}

local displaynames = {
    [1]="Plain",
    [2]="Horizontal Bar 1",
    [3]="Horizontal Bar 2",
    [4]="Horizontal Bar 3",
    [5]="Horizontal Bar 4",
    [6]="Horizontal Bar 5",
    [7]="Horizontal Bar 6",
    [8]="Vertical Bar 1",
    [9]="Vertical Bar 2",
    [10]="Vertical Bar 3",
    [11]="Vertical Bar 4",
    [12]="Vertical Bar 5",
    [13]="Vertical Gradient 1",
    [14]="Vertical Gradient 2",
    [15]="Horizontal Gradient 1",
    [16]="Horizontal Gradient 2",
    [17]="Basic Border",
    [18]="Diagonal Striping",
    [19]="Checkered",
	[20]="SM-Aluminium",
	[21]="SM-Armory",
	[22]="SM-BantoBar",
	[23]="SM-Bars",
	[24]="SM-Bumps",
	[25]="SM-Button",
	[26]="SM-Charcoal",
	[27]="SM-Cilo",
	[28]="SM-Cloud",
	[29]="SM-combo",
	[30]="SM-Comet",
	[31]="SM-Dabs",
	[32]="SM-DarkBottom",
	[33]="SM-Diagonal",
	[34]="SM-Empty",
	[35]="SM-Falumn",
	[36]="SM-Fifths",
	[37]="SM-Flat",
	[38]="SM-Fourths",
	[39]="SM-Frost",
	[40]="SM-Glamour",
	[41]="SM-Glamour2",
	[42]="SM-Glamour3",
	[43]="SM-Glamour4",
	[44]="SM-Glamour5",
	[45]="SM-Glamour6",
	[46]="SM-Glamour7",
	[47]="SM-Glass",
	[48]="SM-Glaze",
	[49]="SM-Glaze2",
	[50]="SM-Gloss",
	[51]="SM-Graphite",
	[52]="SM-Grid",
	[53]="SM-Hatched",
	[54]="SM-Healbot",
	[55]="SM-LiteStep",
	[56]="SM-LiteStepLite",
	[57]="SM-Lyfe",
	[58]="SM-Melli",
	[59]="SM-MelliDark",
	[60]="SM-MelliDarkRough",
	[61]="SM-Minimalist",
	[62]="SM-Otravi",
	[63]="SM-Outline",
	[64]="SM-Perl",
	[65]="SM-Perl2",
	[66]="SM-Pill",
	[67]="SM-Rain",
	[68]="SM-Rocks",
	[69]="SM-Round",
	[70]="SM-Ruben",
	[71]="SM-Runes",
	[72]="SM-Skewed",
	[73]="SM-Smooth",
	[74]="SM-Smoothv2",
	[75]="SM-Smudge",
	[76]="SM-Steel",
	[77]="SM-Striped",
	[78]="SM-Tube",
	[79]="SM-Water",
	[80]="SM-Wglass",
	[81]="SM-Wisps",
	[82]="SM-Xeon",
    [83]="Plain (1.3.5)",
}

local tiled = {
	["squared_diagonal_stripe"]     = true,
    ["squared_checkered"]           = true,
	["tint_square"]					= true,
    ["squared_tint"]                = true,
}

local dims = {
    ["tint_square"]                 = {32, 32},
    ["squared_tint"]                = {1, 1},
    
    ["squared_bar_1"]               = {64, 64},
    ["squared_bar_2"]               = {256, 32},
    ["squared_bar_3"]               = {256, 32},
    ["squared_bar_4"]               = {256, 32},
    ["squared_bar_5"]               = {64, 64},
    ["squared_bar_6"]               = {512, 64},
    
    ["squared_vbar_1"]              = {64, 64},
    ["squared_vbar_2"]              = {32, 256},
    ["squared_vbar_3"]              = {32, 256},
    ["squared_vbar_4"]              = {32, 256},
    ["squared_vbar_5"]              = {64, 64},
    
    ["squared_diagonal_stripe"]     = {64, 64},
    ["squared_checkered"]           = {64, 64},
    
    ["squared_v_gradient"]          = {64, 64},
    ["squared_v_gradient2"]         = {64, 64},
    ["squared_h_gradient"]          = {64, 64},
    ["squared_h_gradient2"]         = {64, 64},
    
    ["squared_border_1"]            = {64, 64},
	
	["SharedMediaAluminium"] = {256,32},
	["SharedMediaArmory"] = {256,32},
	["SharedMediaBantoBar"] = {256,32},
	["SharedMediaBars"] = {256,32},
	["SharedMediaBumps"] = {256,32},
	["SharedMediaButton"] = {256,32},
	["SharedMediaCharcoal"] = {256,32},
	["SharedMediaCilo"] = {256,32},
	["SharedMediaCloud"] = {256,32},
	["SharedMediacombo"] = {256,32},
	["SharedMediaComet"] = {256,32},
	["SharedMediaDabs"] = {256,32},
	["SharedMediaDarkBottom"] = {256,32},
	["SharedMediaDiagonal"] = {256,32},
	["SharedMediaEmpty"] = {256,32},
	["SharedMediaFalumn"] = {256,32},
	["SharedMediaFifths"] = {256,32},
	["SharedMediaFlat"] = {256,32},
	["SharedMediaFourths"] = {256,32},
	["SharedMediaFrost"] = {256,32},
	["SharedMediaGlamour"] = {256,32},
	["SharedMediaGlamour2"] = {256,32},
	["SharedMediaGlamour3"] = {256,32},
	["SharedMediaGlamour4"] = {256,32},
	["SharedMediaGlamour5"] = {256,32},
	["SharedMediaGlamour6"] = {256,32},
	["SharedMediaGlamour7"] = {256,32},
	["SharedMediaGlass"] = {256,32},
	["SharedMediaGlaze"] = {256,32},
	["SharedMediaGlaze2"] = {256,32},
	["SharedMediaGloss"] = {256,32},
	["SharedMediaGraphite"] = {256,32},
	["SharedMediaGrid"] = {256,32},
	["SharedMediaHatched"] = {256,32},
	["SharedMediaHealbot"] = {256,32},
	["SharedMediaLiteStep"] = {256,32},
	["SharedMediaLiteStepLite"] = {256,32},
	["SharedMediaLyfe"] = {256,32},
	["SharedMediaMelli"] = {256,32},
	["SharedMediaMelliDark"] = {256,32},
	["SharedMediaMelliDarkRough"] = {256,32},
	["SharedMediaMinimalist"] = {256,32},
	["SharedMediaOtravi"] = {256,32},
	["SharedMediaOutline"] = {256,32},
	["SharedMediaPerl"] = {256,32},
	["SharedMediaPerl2"] = {256,32},
	["SharedMediaPill"] = {256,32},
	["SharedMediaRain"] = {256,32},
	["SharedMediaRocks"] = {256,32},
	["SharedMediaRound"] = {256,32},
	["SharedMediaRuben"] = {256,32},
	["SharedMediaRunes"] = {256,32},
	["SharedMediaSkewed"] = {256,32},
	["SharedMediaSmooth"] = {256,32},
	["SharedMediaSmoothv2"] = {256,32},
	["SharedMediaSmudge"] = {256,32},
	["SharedMediaSteel"] = {256,32},
	["SharedMediaStriped"] = {256,32},
	["SharedMediaTube"] = {256,32},
	["SharedMediaWater"] = {256,32},
	["SharedMediaWglass"] = {256,32},
	["SharedMediaWisps"] = {256,32},
	["SharedMediaXeon"] = {256,32},
}

local tags = {
    ["tint_square"]                 = {statusbar=true,background=true,verticalbar=true,border=true},
    ["squared_tint"]                = {statusbar=true,background=true,verticalbar=true,border=true},
    
    ["squared_bar_1"]               = {statusbar=true},
    ["squared_bar_2"]               = {statusbar=true},
    ["squared_bar_3"]               = {statusbar=true},
    ["squared_bar_4"]               = {statusbar=true},
    ["squared_bar_5"]               = {statusbar=true},
    ["squared_bar_6"]               = {statusbar=true},
    
    ["squared_vbar_1"]              = {verticalbar=true},
    ["squared_vbar_2"]              = {verticalbar=true},
    ["squared_vbar_3"]              = {verticalbar=true},
    ["squared_vbar_4"]              = {verticalbar=true},
    ["squared_vbar_5"]              = {verticalbar=true},
    
    ["squared_diagonal_stripe"]     = {statusbar=true,background=true},
    ["squared_checkered"]           = {statusbar=true,background=true},
    
    ["squared_v_gradient"]          = {statusbar=true,verticalbar=true,background=true},
    ["squared_v_gradient2"]         = {statusbar=true,verticalbar=true,background=true},
    ["squared_h_gradient"]          = {statusbar=true,verticalbar=true,background=true},
    ["squared_h_gradient2"]         = {statusbar=true,verticalbar=true,background=true},
    
    ["squared_border_1"]            = {border=true},
	
	["SharedMediaAluminium"] = {statusbar=true},
	["SharedMediaArmory"] = {statusbar=true},
	["SharedMediaBantoBar"] = {statusbar=true},
	["SharedMediaBars"] = {statusbar=true},
	["SharedMediaBumps"] = {statusbar=true},
	["SharedMediaButton"] = {statusbar=true},
	["SharedMediaCharcoal"] = {statusbar=true},
	["SharedMediaCilo"] = {statusbar=true},
	["SharedMediaCloud"] = {statusbar=true},
	["SharedMediacombo"] = {statusbar=true},
	["SharedMediaComet"] = {statusbar=true},
	["SharedMediaDabs"] = {statusbar=true},
	["SharedMediaDarkBottom"] = {statusbar=true},
	["SharedMediaDiagonal"] = {statusbar=true},
	["SharedMediaEmpty"] = {statusbar=true},
	["SharedMediaFalumn"] = {statusbar=true},
	["SharedMediaFifths"] = {statusbar=true},
	["SharedMediaFlat"] = {statusbar=true},
	["SharedMediaFourths"] = {statusbar=true},
	["SharedMediaFrost"] = {statusbar=true},
	["SharedMediaGlamour"] = {statusbar=true},
	["SharedMediaGlamour2"] = {statusbar=true},
	["SharedMediaGlamour3"] = {statusbar=true},
	["SharedMediaGlamour4"] = {statusbar=true},
	["SharedMediaGlamour5"] = {statusbar=true},
	["SharedMediaGlamour6"] = {statusbar=true},
	["SharedMediaGlamour7"] = {statusbar=true},
	["SharedMediaGlass"] = {statusbar=true},
	["SharedMediaGlaze"] = {statusbar=true},
	["SharedMediaGlaze2"] = {statusbar=true},
	["SharedMediaGloss"] = {statusbar=true},
	["SharedMediaGraphite"] = {statusbar=true},
	["SharedMediaGrid"] = {statusbar=true},
	["SharedMediaHatched"] = {statusbar=true},
	["SharedMediaHealbot"] = {statusbar=true},
	["SharedMediaLiteStep"] = {statusbar=true},
	["SharedMediaLiteStepLite"] = {statusbar=true},
	["SharedMediaLyfe"] = {statusbar=true},
	["SharedMediaMelli"] = {statusbar=true},
	["SharedMediaMelliDark"] = {statusbar=true},
	["SharedMediaMelliDarkRough"] = {statusbar=true},
	["SharedMediaMinimalist"] = {statusbar=true},
	["SharedMediaOtravi"] = {statusbar=true},
	["SharedMediaOutline"] = {statusbar=true},
	["SharedMediaPerl"] = {statusbar=true},
	["SharedMediaPerl2"] = {statusbar=true},
	["SharedMediaPill"] = {statusbar=true},
	["SharedMediaRain"] = {statusbar=true},
	["SharedMediaRocks"] = {statusbar=true},
	["SharedMediaRound"] = {statusbar=true},
	["SharedMediaRuben"] = {statusbar=true},
	["SharedMediaRunes"] = {statusbar=true},
	["SharedMediaSkewed"] = {statusbar=true},
	["SharedMediaSmooth"] = {statusbar=true},
	["SharedMediaSmoothv2"] = {statusbar=true},
	["SharedMediaSmudge"] = {statusbar=true},
	["SharedMediaSteel"] = {statusbar=true},
	["SharedMediaStriped"] = {statusbar=true},
	["SharedMediaTube"] = {statusbar=true},
	["SharedMediaWater"] = {statusbar=true},
	["SharedMediaWglass"] = {statusbar=true},
	["SharedMediaWisps"] = {statusbar=true},
	["SharedMediaXeon"] = {statusbar=true},
}

local LSA = LibStub("LibSharedAssets")
if not LSA then return end

for k,texName in ipairs(textures) do
	local metadata = {
			displayname = displaynames[k],
			size = dims[texName],
			tiled = tiled[texName] or false,
			tags = tags[texName],
		}
	local result = LSA:RegisterTexture(texName, metadata)
	if not result then
		LSA:AddMetadata(texName, {displayname = displaynames[k]})
	end
end