--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]

--
-- The localization information present within this file is automatically
-- packaged by the CurseForge packager.
--
-- Incorrect or missing translations can be updated here:
-- http://war.curseforge.com/projects/pure/localization/
--

local T = LibStub("WAR-AceLocale-3.0"):NewLocale("Pure", "deDE")
if not T then return end

T["About Pure"] = L"Über Pure"
T["Action Point Format:"] = L"Aktionspunkt Format:"
T["Action Point Texture:"] = L"Aktionspunkt Textur:"
T["Action Points Texture Color"] = L"Aktionspunkte Texturfarbe:"
T["Active Profile:"] = L"Aktives Profil:"
T["Alpha"] = L"Transparenz"
T["Anchor Column Offset:"] = L"Verschiebung Spalten-Anker"
T["Anchor Row Offset:"] = L"Verschiebung Reihen-Anker"
T["Apply"] = L"Anwenden"
T["Archtype:"] = L"Archetyp:"
T["Archtypes"] = L"Archetypen"
T["Are you sure?"] = L"Bist du sicher?"
T["Blue"] = L"Blau"
T["Bottom"] = L"unten"
T["Cancel"] = L"Abbrechen"
T["Cast Pet Heal On Click"] = L"Begleiter-Heilung per Klick"
T["Clear Friendly Target On Click"] = L"Hebe freundliches Ziel nach Klick auf"
T["Click Through Unit Frame"] = L"Durch Unit Frames hindurchklicken"
T["Close"] = L"Schließen"
T["Colors"] = L"Farben"
T["Coming Soon!"] = L"Demnächst verfügbar!"
T["Configure Class/Archtypes:"] = L"Klassen/Archetypen konfigurieren:"
T["Copy Settings From:"] = L"Kopiere Einstellungen von:"
T["Current Hitpoints:"] = L"Aktuelle Trefferpunkte"
T["Current Profile:"] = L"Aktuelles Profil:"
T["Default"] = L"Standard"
T["Direction From Target"] = L"Richtung vom Ziel"
T["Dispel Highlighting"] = L"Hervorhebung von Verbannungen"
T["Distance"] = L"Entfernung"
T["Distance From Target"] = L"Entfernung vom Ziel"
T["Down"] = L"runter"
T["Effect Anchor:"] = L"Effekte Anker:"
T["Effect Columns:"] = L"Effekte Spalten:"
-- T["Effect Frame Alpha"] = L""
-- T["Effect Frame Font Alpha"] = L""
T["Effect Height:"] = L"Effekte Höhe:"
T["Effect Rows:"] = L"Effekte Reihen:"
T["Effect Width:"] = L"Effekte Weite:"
T["Effects"] = L"Effekte"
T["Enable Class Archtype Coloring"] = L"Aktiviere Klassen Archetypen Färbung"
T["Enable Class Archtype Coloring - Hitpoints"] = L"Einfärben der Lebenspunkte nach Klassentyp"
T["Enable Class Archtype Coloring - Name"] = L"Einfärben des Namens nach Klassentyp"
T["Enable Dispel Highlighting"] = L"Aktiviere Hervorhebung von Verbannungen"
T["Enable Effect Tracker"] = L"Effekttracker aktivieren"
T["Enable Friendly Target HUD"] = L"Aktiviere  Freundliches Ziel HUD"
T["Enable Friendly Target HUD Unit Frame"] = L"Aktiviere Freundliches Ziel HUD"
T["Enable Friendly Target Unit Frame"] = L"Aktiviere Freundliches Ziel Fenster"
T["Enable Group Pet Unit Frame"] = L"Akriviere Gruppen Begleiter Fenster"
T["Enable Group Unit Frame"] = L"Aktiviere Gruppen Fenster"
T["Enable Hostile Target HUD"] = L"Aktiviere Feindliches Ziel HUD"
T["Enable Hostile Target HUD Unit Frame"] = L"Aktiviere Feindliches Ziel HUD"
T["Enable Hostile Target Unit Frame"] = L"Aktiviere Feindliches Ziel Fenster"
T["Enable Player Pet Target Unit Frame"] = L"Aktiviere Spieler Begleiter Zielfenster"
T["Enable Player Pet Unit Frame"] = L"Aktiviere Begleiter Fenster"
T["Enable Player Unit Frame"] = L"Spieler Unitframe aktivieren:"
T["Enable Pure"] = L"Pure aktivieren"
T["Enable Target Highlighting"] = L"Aktiviere Ziel Hervorhebung"
T["Format:"] = L"Format:"
T["Formatting"] = L"Formatierung"
T["Friendly Target"] = L"Freundliches Ziel"
T["Friendly Target HUD"] = L"Freundliches Ziel HUD"
-- T["Friendly Target HUD:"] = L""
T["Friendly Target:"] = L"Befreundetes Ziel"
T["General"] = L"Allgemein"
T["Green"] = L"Grün"
T["Group"] = L"Gruppe"
T["Group Leader Indicator:"] = L"Gruppenleiter Indikator:"
T["Group Pet"] = L"Gruppen Begleiter"
T["Group Pet Window"] = L"Gruppen Begleiter"
T["Group Pet:"] = L"Gruppen Pet:"
T["Group Window"] = L"Gruppenfenster"
T["Group:"] = L"Gruppe:"
T["Growth Direction:"] = L"Erweiterungsrichtung"
T["Hit Point Format:"] = L"Trefferpunkt Format:"
T["Hit Point Texture:"] = L"Trefferpunkt Textur:"
T["Hit Points Texture Color"] = L"Trefferpunkte Texturfarbe:"
T["Horizontal Growth Offset:"] = L"Verschiebung der horizontalen Erweiterung"
T["Hostile Target"] = L"Feindliches Ziel"
T["Hostile Target HUD"] = L"Feindliches Ziel HUD"
-- T["Hostile Target HUD:"] = L""
T["Hostile Target:"] = L"Feindliches Ziel:"
T["Left"] = L"links"
T["Morale Color"] = L"Moral Farbe"
T["NOTE: Profile changes take effect immediately!"] = L"HINWEIS: Profiländerungen werden sofort in Kraft treten!"
T["None"] = L"Nichts"
T["Offline"] = L"offline"
T["Open Parties Window"] = L"Offene Gruppen Fenster"
T["Pet Target"] = L"Begleiter Ziel"
T["Player"] = L"Spieler"
T["Player Pet"] = L"Spieler Begleiter"
T["Player Pet Target"] = L"Spieler Begleiter Ziel"
T["Player Pet Target:"] = L"Ziel des Spieler Pets:"
T["Player:"] = L"Spieler:"
T["Playet Pet:"] = L"Spieler Pet:"
T["Profiles"] = L"Profile"
T["Pure %s initialized."] = L"Pure %s initalisiert"
T["Pure - Configuration"] = L"Pure-Konfiguration"
T["Red"] = L"Rot"
T["Reset Profile"] = L"Profil zurücksetzen"
T["Revert"] = L"Rückgängig"
T["Right"] = L"rechts"
T["RvR Flag Color"] = L"Farbe der RvR Kennzeichnung"
T["Set Active Profile:"] = L"Setze aktives Profil:"
T["Show Class Names"] = L"Zeige Klassen Namen"
T["Show Effect Durations"] = L"Effektdauer anzeigen"
T["Show In Scenarios"] = L"Anzeige in Szenarien"
T["Show In Warband"] = L"Im Kriegstrupp anzeigen"
T["Show Mythic Style Border"] = L"Mythictypische Randverzierung anzeigen"
T["Show Player In Group"] = L"Spieler in Gruppe anzeigen"
T["Show Self Cast Effects Only"] = L"Zeige nur eigene Effekte"
-- T["Show Sigil Requirement"] = L""
-- T["Show When In Siege Engine"] = L""
T["Show When Out Of Combat"] = L"Anzeigen wenn nicht im Kampf" -- Needs review
T["Target"] = L"Ziel"
T["Target Highlighting"] = L"Ziel Hervorhebung"
T["Templates"] = L"Vorlagen"
T["Textures"] = L"Texturen"
T["Top"] = L"oben"
T["Unit Frame Alpha"] = L"Unitframe Transparenz"
-- T["Unit Frame Font Alpha"] = L""
-- T["Unit Frame Templates"] = L""
T["Up"] = L"hoch"
T["Use Squared archtype coloring (Requires Squared)"] = L"Verwende Squared Archetyp Farben (Squared benötigt)"
T["Vertical Growth Offset:"] = L"Verschiebung der vertikalen Erweiterung"
T["WARNING: Clicking this button will restore the current profile back to default values!"] = L"WARNUNG: Dieser Knopf wird das aktuelle Profil auf Standartwerte zurücksetzen!"

