--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]

--
-- The localization information present within this file is automatically
-- packaged by the CurseForge packager.
--
-- Incorrect or missing translations can be updated here:
-- http://war.curseforge.com/projects/pure/localization/
--

local T = LibStub("WAR-AceLocale-3.0"):NewLocale("Pure", "esES")
if not T then return end

T["About Pure"] = L"Sobre Pure"
T["Action Point Format:"] = L"Formato Punto Acción:"
T["Action Point Texture:"] = L"Texturas Puntos de Acción"
T["Action Points Texture Color"] = L"Color Textura Puntos Acción"
T["Active Profile:"] = L"Perfil Activo:"
T["Alpha"] = L"Alfa"
T["Anchor Column Offset:"] = L"Desplazamiento Anclaje Columna:"
T["Anchor Row Offset:"] = L"Desplazamiento Anclaje Fila:"
T["Apply"] = L"Aplicar"
T["Archtype:"] = L"Arquetipo"
T["Archtypes"] = L"Arquetipos"
T["Are you sure?"] = L"¿Estás Seguro?"
T["Blue"] = L"Azul"
T["Bottom"] = L"Abajo de todo"
T["Cancel"] = L"Cancelar"
T["Cast Pet Heal On Click"] = L"Lanza Cura Mascota al Cliquear"
T["Clear Friendly Target On Click"] = L"Deselecciona Objetivo Amigo al Cliquear"
T["Click Through Unit Frame"] = L"Click A Través Barra"
T["Close"] = L"Cerrar"
T["Colors"] = L"Colores"
T["Coming Soon!"] = L"¡ Muy Pronto !"
T["Configure Class/Archtypes:"] = L"Configurar Clase/Arquetipos"
T["Copy Settings From:"] = L"Copiar Configuración Desde:"
T["Current Hitpoints:"] = L"Puntos de Vida Actuales:"
T["Current Profile:"] = L"Perfil Actual:"
T["Default"] = L"Por Defecto"
T["Direction From Target"] = L"Distancia a Objetivo"
T["Dispel Highlighting"] = L"Resaltar Disipaciones Conjuros"
T["Distance"] = L"Distancia"
T["Distance From Target"] = L"Distancia a Objetivo"
T["Down"] = L"Abajo"
T["Effect Anchor:"] = L"Anclar Efecto"
T["Effect Columns:"] = L"Columnas de Efecto"
T["Effect Frame Alpha"] = L"Alfa Barra Efecto"
T["Effect Frame Font Alpha"] = L"Alfa Fuente Barra Efecto"
T["Effect Height:"] = L"Altura de Efecto"
T["Effect Rows:"] = L"Filas de Efecto"
T["Effect Width:"] = L"Anchura de Efecto"
T["Effects"] = L"Efectos"
T["Enable Class Archtype Coloring"] = L"Activar Coloración Arquetipo Clase"
-- T["Enable Class Archtype Coloring - Hitpoints"] = L""
-- T["Enable Class Archtype Coloring - Name"] = L""
T["Enable Dispel Highlighting"] = L"Habilitar Resalte Disipaciones Conjuros"
T["Enable Effect Tracker"] = L"Habilitar Seguimiento de Efectos"
T["Enable Friendly Target HUD"] = L"Activar HUD Objetivo Amigo"
T["Enable Friendly Target HUD Unit Frame"] = L"Activa Barra HUD Objetivo Amigo"
T["Enable Friendly Target Unit Frame"] = L"Activar Barra Objetivo Amigo"
T["Enable Group Pet Unit Frame"] = L"Activar Barra Mascota Grupo"
T["Enable Group Unit Frame"] = L"Activar Barra Grupo"
T["Enable Hostile Target HUD"] = L"Activar HUD Objetivo Enemigo"
T["Enable Hostile Target HUD Unit Frame"] = L"Activar Barra HUD Objetivo Enemigo"
T["Enable Hostile Target Unit Frame"] = L"Activar Barra Objetivo Enemigo"
T["Enable Player Pet Target Unit Frame"] = L"Activar Barra Objetivo Mascota Jugador"
T["Enable Player Pet Unit Frame"] = L"Activar Barra Mascota Jugador"
T["Enable Player Unit Frame"] = L"Habilitar Barra de Jugador"
T["Enable Pure"] = L"Habilitar Pure"
T["Enable Target Highlighting"] = L"Activar Resaltado Objetivo"
T["Format:"] = L"Formato:"
T["Formatting"] = L"Formateo"
T["Friendly Target"] = L"Aliado or Objetivo Aliado"
T["Friendly Target HUD"] = L"HUD Objetivo Amigo"
-- T["Friendly Target HUD:"] = L""
-- T["Friendly Target:"] = L""
T["General"] = L"General"
T["Green"] = L"Verde"
T["Group"] = L"Grupo"
T["Group Leader Indicator:"] = L"Indicador Líder Grupo"
T["Group Pet"] = L"Mascota Grupo"
T["Group Pet Window"] = L"Ventana Mascota de Grupo"
-- T["Group Pet:"] = L""
T["Group Window"] = L"Ventana de Grupo"
-- T["Group:"] = L""
T["Growth Direction:"] = L"Dirección Crecimiento"
T["Hit Point Format:"] = L"Formato Punto Vida:"
T["Hit Point Texture:"] = L"Texturas Puntos de Vida"
T["Hit Points Texture Color"] = L"Color Textura Puntos Vida"
T["Horizontal Growth Offset:"] = L"Desplazamiento Crecimiento Horizontal:"
T["Hostile Target"] = L"Enemigo , or Objetivo Hostil"
T["Hostile Target HUD"] = L"HUD Objetivo Enemigo"
-- T["Hostile Target HUD:"] = L""
-- T["Hostile Target:"] = L""
T["Left"] = L"Izquierda"
T["Morale Color"] = L"Color Moral"
T["NOTE: Profile changes take effect immediately!"] = L"NOTA: ¡ Los cambios al Perfil tendrán efectos inmediatos !"
T["None"] = L"Ninguno"
T["Offline"] = L"Fuera de Línea"
T["Open Parties Window"] = L"Ventana de grupos abiertos"
T["Pet Target"] = L"Objetivo Mascota"
T["Player"] = L"Jugador"
T["Player Pet"] = L"Mascota Jugador"
T["Player Pet Target"] = L"Objetivo de Mascota Jugador"
-- T["Player Pet Target:"] = L""
-- T["Player:"] = L""
-- T["Playet Pet:"] = L""
T["Profiles"] = L"Perfiles"
T["Pure %s initialized."] = L"Pure %s Activado"
T["Pure - Configuration"] = L"Pure - Configuracion"
T["Red"] = L"Rojo"
T["Reset Profile"] = L"Resetear Perfil"
T["Revert"] = L"Deshacer"
T["Right"] = L"Derecha"
T["RvR Flag Color"] = L"Color Bandera RvR"
T["Set Active Profile:"] = L"Fija Perfil Activo:"
T["Show Class Names"] = L"Nombres Clases Visibles"
T["Show Effect Durations"] = L"Mostrar Duraciones Efectos"
T["Show In Scenarios"] = L"Visible en Escenarios"
T["Show In Warband"] = L"Mostrar en Warband"
T["Show Mythic Style Border"] = L"Mostrar Borde Estilo Mythic"
T["Show Player In Group"] = L"Muestra Jugador En Grupo"
T["Show Self Cast Effects Only"] = L"Mostrar Sólo Efectos Autoaplicados"
-- T["Show Sigil Requirement"] = L""
-- T["Show When In Siege Engine"] = L""
-- T["Show When Out Of Combat"] = L""
T["Target"] = L"Objetivo"
T["Target Highlighting"] = L"Resaltado Objetivo"
T["Templates"] = L"Plantillas"
T["Textures"] = L"Texturas"
T["Top"] = L"Arriba de todo"
T["Unit Frame Alpha"] = L"Alfa Barra Unidad"
T["Unit Frame Font Alpha"] = L"Alfa Fuente Barra"
-- T["Unit Frame Templates"] = L""
T["Up"] = L"Arriba"
T["Use Squared archtype coloring (Requires Squared)"] = L"Usar colores de arquetipo (Squared Requerido)"
T["Vertical Growth Offset:"] = L"Desplazamiento Crecimiento Vertical:"
T["WARNING: Clicking this button will restore the current profile back to default values!"] = L"AVISO: ¡ Apretar este botón devolverá el perfil actual a los valores por defecto !"

