--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]

--
-- The localization information present within this file is automatically
-- packaged by the CurseForge packager.
--
-- Incorrect or missing translations can be updated here:
-- http://war.curseforge.com/projects/pure/localization/
--

local T = LibStub("WAR-AceLocale-3.0"):NewLocale("Pure", "itIT")
if not T then return end

T["About Pure"] = L"Riguardo Pure"
T["Action Point Format:"] = L"Formato Punti Azione:"
T["Action Point Texture:"] = L"Sfondo barra Punti Azione:"
T["Action Points Texture Color"] = L"Colore barra Punti Azione"
T["Active Profile:"] = L"Profilo attivo:"
T["Alpha"] = L"Opacità"
T["Anchor Column Offset:"] = L"Offset colonne:"
T["Anchor Row Offset:"] = L"Offset righe:"
T["Apply"] = L"Applica"
T["Archtype:"] = L"Archetipo:"
T["Archtypes"] = L"Archetipi"
T["Are you sure?"] = L"Sei sicuro?"
T["Blue"] = L"Blu"
T["Bottom"] = L"Sotto"
T["Cancel"] = L"Cancella"
T["Cast Pet Heal On Click"] = L"Cura famiglio con mouseclick"
T["Clear Friendly Target On Click"] = L"Rimuovi bersaglio amico con mouseclick"
T["Click Through Unit Frame"] = L"Click oltre l'interfaccia"
T["Close"] = L"Chiudi"
T["Colors"] = L"Colori"
T["Coming Soon!"] = L"Prossimamente!"
T["Configure Class/Archtypes:"] = L"Configura classe/archetipi:"
T["Copy Settings From:"] = L"Copia impostazioni da:"
T["Current Hitpoints:"] = L"Punti Ferita attuali:"
T["Current Profile:"] = L"Profilo attuale:"
T["Default"] = L"Predefinito"
T["Direction From Target"] = L"Direzione dal bersaglio"
T["Dispel Highlighting"] = L"Dispel evidenziati"
T["Distance"] = L"Distanza"
T["Distance From Target"] = L"Distanza dal bersaglio"
T["Down"] = L"Giù"
T["Effect Anchor:"] = L"Posizionamento effetti:"
T["Effect Columns:"] = L"Numero colonne:"
T["Effect Frame Alpha"] = L"Opacità effetti"
T["Effect Frame Font Alpha"] = L"Opacità testo effetti"
T["Effect Height:"] = L"Altezza effetto:"
T["Effect Rows:"] = L"Numero righe:"
T["Effect Width:"] = L"Larghezza effetto:"
T["Effects"] = L"Effetti"
T["Enable Class Archtype Coloring"] = L"Abilita colorazione per archetipo"
T["Enable Class Archtype Coloring - Hitpoints"] = L"Abilita colorazione per archetipo - Punti Ferita"
T["Enable Class Archtype Coloring - Name"] = L"Abilita colorazione per archetipo - Nome"
T["Enable Dispel Highlighting"] = L"Abilita dispel evidenziati"
T["Enable Effect Tracker"] = L"Abilita rilevamento effetti"
T["Enable Friendly Target HUD"] = L"Abilita HUD bersaglio amico"
T["Enable Friendly Target HUD Unit Frame"] = L"Abilita interfaccia \"HUD bersaglio amico\""
T["Enable Friendly Target Unit Frame"] = L"Abilita interfaccia \"Bersaglio amico\""
T["Enable Group Pet Unit Frame"] = L"Abilita interfaccia \"Famigli del gruppo\""
T["Enable Group Unit Frame"] = L"Abilita interfaccia \"Gruppo\""
T["Enable Hostile Target HUD"] = L"Abilita HUD bersaglio nemico"
T["Enable Hostile Target HUD Unit Frame"] = L"Abilita interfaccia \"HUD bersaglio nemico\""
T["Enable Hostile Target Unit Frame"] = L"Abilita interfaccia \"Bersaglio nemico\""
T["Enable Player Pet Target Unit Frame"] = L"Abilita interfaccia \"Bersaglio del famiglio\""
T["Enable Player Pet Unit Frame"] = L"Abilita interfaccia \"Famiglio del giocatore\""
T["Enable Player Unit Frame"] = L"Abilita interfaccia \"Giocatore\""
T["Enable Pure"] = L"Abilita Pure"
T["Enable Target Highlighting"] = L"Abilita bersaglio evidenziato"
T["Format:"] = L"Formato:"
T["Formatting"] = L"Formattazione"
T["Friendly Target"] = L"Bersaglio amico"
T["Friendly Target HUD"] = L"HUD bersaglio amico"
T["Friendly Target HUD:"] = L"HUD bersaglio amico:"
T["Friendly Target:"] = L"Bersaglio amico:"
T["General"] = L"Generale"
T["Green"] = L"Verde"
T["Group"] = L"Gruppo"
T["Group Leader Indicator:"] = L"Indicatore del capo-gruppo:"
T["Group Pet"] = L"Famigli del gruppo"
T["Group Pet Window"] = L"Finestra dei famigli del gruppo"
T["Group Pet:"] = L"Famigli del gruppo:"
T["Group Window"] = L"Finestra del gruppo"
T["Group:"] = L"Gruppo:"
T["Growth Direction:"] = L"Direzione riempimento:"
T["Hit Point Format:"] = L"Formato Punti Ferita:"
T["Hit Point Texture:"] = L"Sfondo barra Punti Ferita:"
T["Hit Points Texture Color"] = L"Colore barra Punti Ferita"
T["Horizontal Growth Offset:"] = L"Offset riempimento orizzontale:"
T["Hostile Target"] = L"Bersaglio nemico"
T["Hostile Target HUD"] = L"HUD bersaglio nemico"
T["Hostile Target HUD:"] = L"HUD bersaglio nemico:"
T["Hostile Target:"] = L"Bersaglio nemico:"
T["Left"] = L"Sinistra"
T["Morale Color"] = L"Colore del Morale"
T["NOTE: Profile changes take effect immediately!"] = L"NOTA: i cambiamenti al profilo avvengono immediatamente!"
T["None"] = L"Nessuno"
T["Offline"] = L"Offline"
T["Open Parties Window"] = L"Apri finestra gruppo"
T["Pet Target"] = L"Bersaglio del famiglio"
T["Player"] = L"Giocatore"
T["Player Pet"] = L"Famiglio del giocatore"
T["Player Pet Target"] = L"Bersaglio del famiglio"
T["Player Pet Target:"] = L"Bersaglio del famiglio:"
T["Player:"] = L"Giocatore:"
T["Playet Pet:"] = L"Famiglio del giocatore:"
T["Profiles"] = L"Profili"
T["Pure %s initialized."] = L"Pure %s inizializzato."
T["Pure - Configuration"] = L"Pure - Configurazione"
T["Red"] = L"Rosso"
T["Reset Profile"] = L"Azzera profilo"
T["Revert"] = L"Ripristina"
T["Right"] = L"Destra"
T["RvR Flag Color"] = L"Colore simbolo RvR"
T["Set Active Profile:"] = L"Imposta profilo attivo:"
T["Show Class Names"] = L"Mostra nomi delle classi"
T["Show Effect Durations"] = L"Mostra durata degli effetti"
T["Show In Scenarios"] = L"Mostra negli Scenari"
T["Show In Warband"] = L"Mostra in plotone"
T["Show Mythic Style Border"] = L"Mostra bordo stile-Mythic"
T["Show Player In Group"] = L"Mostra giocatore nel gruppo"
T["Show Self Cast Effects Only"] = L"Mostra solo i tuoi effetti"
T["Show Sigil Requirement"] = L"Mostra requisiti di sigillo"
-- T["Show When In Siege Engine"] = L""
T["Show When Out Of Combat"] = L"Mostra quando fuori combattimento"
T["Target"] = L"Bersaglio"
T["Target Highlighting"] = L"Bersaglio evidenziato"
T["Templates"] = L"Modelli"
T["Textures"] = L"Textures"
T["Top"] = L"Sopra"
T["Unit Frame Alpha"] = L"Opacità interfaccia"
T["Unit Frame Font Alpha"] = L"Opacità testo interfaccia"
T["Unit Frame Templates"] = L"Modelli interfaccia"
T["Up"] = L"Su"
T["Use Squared archtype coloring (Requires Squared)"] = L"Usa modello di colori di Squared (richiede Squared)"
T["Vertical Growth Offset:"] = L"Offset riempimento verticale:"
T["WARNING: Clicking this button will restore the current profile back to default values!"] = L"ATTENZIONE: premendo questo pulsante il profilo attuale tornerà ai valori iniziali!"

