--[[
	This application is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    The applications is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with the applications.  If not, see <http://www.gnu.org/licenses/>.
--]]

--
-- The localization information present within this file is automatically
-- packaged by the CurseForge packager.
--
-- Incorrect or missing translations can be updated here:
-- http://war.curseforge.com/projects/pure/localization/
--

local T = LibStub("WAR-AceLocale-3.0"):NewLocale("Pure", "koKR")
if not T then return end

-- T["About Pure"] = L""
-- T["Action Point Format:"] = L""
-- T["Action Point Texture:"] = L""
-- T["Action Points Texture Color"] = L""
-- T["Active Profile:"] = L""
-- T["Alpha"] = L""
-- T["Anchor Column Offset:"] = L""
-- T["Anchor Row Offset:"] = L""
-- T["Apply"] = L""
-- T["Archtype:"] = L""
-- T["Archtypes"] = L""
-- T["Are you sure?"] = L""
-- T["Blue"] = L""
-- T["Bottom"] = L""
-- T["Cancel"] = L""
-- T["Cast Pet Heal On Click"] = L""
-- T["Clear Friendly Target On Click"] = L""
-- T["Click Through Unit Frame"] = L""
-- T["Close"] = L""
-- T["Colors"] = L""
-- T["Coming Soon!"] = L""
-- T["Configure Class/Archtypes:"] = L""
-- T["Copy Settings From:"] = L""
-- T["Current Hitpoints:"] = L""
-- T["Current Profile:"] = L""
-- T["Default"] = L""
-- T["Direction From Target"] = L""
-- T["Dispel Highlighting"] = L""
-- T["Distance"] = L""
-- T["Distance From Target"] = L""
-- T["Down"] = L""
-- T["Effect Anchor:"] = L""
-- T["Effect Columns:"] = L""
-- T["Effect Frame Alpha"] = L""
-- T["Effect Frame Font Alpha"] = L""
-- T["Effect Height:"] = L""
-- T["Effect Rows:"] = L""
-- T["Effect Width:"] = L""
-- T["Effects"] = L""
-- T["Enable Class Archtype Coloring"] = L""
-- T["Enable Class Archtype Coloring - Hitpoints"] = L""
-- T["Enable Class Archtype Coloring - Name"] = L""
-- T["Enable Dispel Highlighting"] = L""
-- T["Enable Effect Tracker"] = L""
-- T["Enable Friendly Target HUD"] = L""
-- T["Enable Friendly Target HUD Unit Frame"] = L""
-- T["Enable Friendly Target Unit Frame"] = L""
-- T["Enable Group Pet Unit Frame"] = L""
-- T["Enable Group Unit Frame"] = L""
-- T["Enable Hostile Target HUD"] = L""
-- T["Enable Hostile Target HUD Unit Frame"] = L""
-- T["Enable Hostile Target Unit Frame"] = L""
-- T["Enable Player Pet Target Unit Frame"] = L""
-- T["Enable Player Pet Unit Frame"] = L""
-- T["Enable Player Unit Frame"] = L""
-- T["Enable Pure"] = L""
-- T["Enable Target Highlighting"] = L""
-- T["Format:"] = L""
-- T["Formatting"] = L""
-- T["Friendly Target"] = L""
-- T["Friendly Target HUD"] = L""
-- T["Friendly Target HUD:"] = L""
-- T["Friendly Target:"] = L""
-- T["General"] = L""
-- T["Green"] = L""
-- T["Group"] = L""
-- T["Group Leader Indicator:"] = L""
-- T["Group Pet"] = L""
-- T["Group Pet Window"] = L""
-- T["Group Pet:"] = L""
-- T["Group Window"] = L""
-- T["Group:"] = L""
-- T["Growth Direction:"] = L""
-- T["Hit Point Format:"] = L""
-- T["Hit Point Texture:"] = L""
-- T["Hit Points Texture Color"] = L""
-- T["Horizontal Growth Offset:"] = L""
-- T["Hostile Target"] = L""
-- T["Hostile Target HUD"] = L""
-- T["Hostile Target HUD:"] = L""
-- T["Hostile Target:"] = L""
-- T["Left"] = L""
-- T["Morale Color"] = L""
-- T["NOTE: Profile changes take effect immediately!"] = L""
-- T["None"] = L""
-- T["Offline"] = L""
-- T["Open Parties Window"] = L""
-- T["Pet Target"] = L""
-- T["Player"] = L""
-- T["Player Pet"] = L""
-- T["Player Pet Target"] = L""
-- T["Player Pet Target:"] = L""
-- T["Player:"] = L""
-- T["Playet Pet:"] = L""
-- T["Profiles"] = L""
-- T["Pure %s initialized."] = L""
-- T["Pure - Configuration"] = L""
-- T["Red"] = L""
-- T["Reset Profile"] = L""
-- T["Revert"] = L""
-- T["Right"] = L""
-- T["RvR Flag Color"] = L""
-- T["Set Active Profile:"] = L""
-- T["Show Class Names"] = L""
-- T["Show Effect Durations"] = L""
-- T["Show In Scenarios"] = L""
-- T["Show In Warband"] = L""
-- T["Show Mythic Style Border"] = L""
-- T["Show Player In Group"] = L""
-- T["Show Self Cast Effects Only"] = L""
-- T["Show Sigil Requirement"] = L""
-- T["Show When In Siege Engine"] = L""
-- T["Show When Out Of Combat"] = L""
-- T["Target"] = L""
-- T["Target Highlighting"] = L""
-- T["Templates"] = L""
-- T["Textures"] = L""
-- T["Top"] = L""
-- T["Unit Frame Alpha"] = L""
-- T["Unit Frame Font Alpha"] = L""
-- T["Unit Frame Templates"] = L""
-- T["Up"] = L""
-- T["Use Squared archtype coloring (Requires Squared)"] = L""
-- T["Vertical Growth Offset:"] = L""
-- T["WARNING: Clicking this button will restore the current profile back to default values!"] = L""

