--[[
  MGRemix (Miracle Grow Remix) version 2.33
  by Irinia of Volkmar
  MGRemix puts all the functionality of the cultivation interface into a small
  window.  Also added are quick item selection and one-click repeat

  This file, Localization.lua, contains all of the text so that it can be
  translated and replaced easily.
]]--


MiracleGrow2.T[SystemData.Settings.Language.FRENCH]={
	cmenus = {
		config = L"Configurer",
		count = L"{1}x",
		fillallrhya = L"Meilleur Rhya",
		fillalltitle = L"Insérer tous les additifs",
		fillallvendor = L"Meilleur vendeur",
		level = L"Niv{1}",
		lvlandrarity = L"Niv.{1} {2}",
	},
	config = {
		enabletoggle = L"Activer le bouton d'affichage",
		langdefault = L"Par défaut",
		layoutinstructions = L"Glisser\
et\
déposer",
		maxlvl = L"Niveau {1} ou inférieur",
		maxlvl0 = L"Utilisable uniquement",
		minlvl = L"Niveau {1} ou supérieur",
		minlvl0 = L"Aucune limitation minimale",
		plotcountlabel = L"blocs",
		plothorizontal = L"Empiler les blocs de gauche à droite",
		plotlines = L"Afficher les séparateurs",
		plotsize = L"Taille de bloc",
		plotspacing = L"Espacement",
		plotsquare = L"Disposer en carré",
		plotvertical = L"Empiler les blocs de haut en bas",
		presetdefault = L"Par défaut",
		presetgo = L"Choisir",
		presetlayclassic = L"Remix Classique",
		presetlaycompact = L"Compact",
		presetlaylargebar = L"Grande Barre de Progression",
		presetlayplantme = L"PlantMe Classique",
		presetlayvert = L"Vertical",
		progback = L"Arrière",
		progbottomtotop = L"Empiler de bas en haut",
		progfill = L"Avant",
		proghide = L"Masquer la barre de progression",
		proglefttoright = L"Empiler de gauche à droite",
		progrighttoleft = L"Empiler de droite à gauche",
		progtoptobottom = L"Empiler de haut en bas",
		reserveenable = L"Essayer de préserver une réserve de graines",
		reserveunits = L"graines",
		sectionautoreap = L"Conversion automatique",
		sectioningredient = L"Liste d'ingrédients",
		sectionlanguage = L"Langue",
		sectionplots = L"Disposition de bloc",
		sectionprog = L"Barre de progression",
		sectionsound = L"Sons d'avancement",
		sectionwindow = L"Fenêtre principale",
		show = L"Afficher la fenêtre",
		sound1label = L"Phase terminée",
		sound2label = L"Prêt à récolter",
		soundenable = L"Activer les sons",
		soundtest = L"Tester",
		soundtip1 = L"Le son sonnu le plus proche est {1}",
		soundtip2 = L"Les sons connus les plus proches sont {1} et {2}",
		soundtipfail = L"Aucun son valide connu pour {1}",
		tablayout = L"Apparence",
		tablayoutdesc = L"Apparence de la fenêtre principale",
		tabpreset = L"Profils",
		tabpresetdesc = L"Choisir les profils de réglages et d'apparence",
		tabsettings = L"Réglages",
		tabsettingsdesc = L"Réglages généraux",
		throb = L"Activer l'effet d'avertissement",
		throbcolor = L"Couleur",
		visibility = L"Visibilité",
		["x"] = L"x",
		["y"] = L"y",
	},
	general = {
		mgremix = L"Miracle Grow Remix",
		mgremixdesc = L"Panel pour une culture facile et rapide",
		thislanguage = L"Français",
	},
	help = {
		layarrange = L"Vous pouvez ici déterminer comment les blocs seront agancés sur la fenêtre principale.\
* Vous pouvez empiler les blocs les uns au dessus des autres, les uns à la suite des autres ou sur deux colonnes.\
* Si vous n'empilez pas les blocs sur deux colonnes, vous pouvez en afficher moins de quatre. Seuls les blocs demandant le plus d'attention seront affichés.\
* Vous pouvez choisir d'ajouter des lignes de séparation entre les blocs afin de mieux marquer quand un bloc s'arrête et un autre commence.\
* Vous pouvez définir l'espacement entre chaque bloc et entre les blocs et le bord de la fenêtre principale.",
		laydraganddrop = L"Cette zone affiche comment seront agancés les éléments pour chaque bloc. Vous pouvez faire glisser-déposer chaque élément où vous souhaitez le positionner. Si vous faites glisser un élément en dehors du bloc, il sera déplacé dans la zone d'éléments inutilisés sur la droite. La taille de bloc est paramétrée par le réglage *Taille de bloc* sur la droite. Si vous rendez la taille de bloc trop étroite pour contenir tous les éléments, ces derniers seront colorés en rouge et n'apparaîtront pas dans le bloc actuel. Vous pouvez également avoir un aperçu de la barre de progression ici-même.",
		layplotsize = L"Ces réglages permettent de configurer la taille du bloc représenté sur la gauche. Vous pouvez agrandir la taille de bloc afin d'y ajouter plus d'éléments ou plus d'espace entre eux, ou au contraire la réduire après avoir retiré certains éléments afin qu'ils occupent moins de place.",
		layprog = L"Ces réglages vous permettent de personnaliser la barre de progression. Vous pouvez avoir un aperçu de vos réglages ci-dessus.",
		layprogdim = L"Vous pouvez ici définir l'emplacement où la barre de progression apparaîtra aussi bien que la taille qu'elle aura. Chaque paire x/y définit la position d'un coin de la barre.",
		layprogfill = L"Vous pouvez ici définir la direction que suivra la barre de progression ou choisir de la masquer complètement.",
		layprogtex = L"Vous pouvez ici sélectionner quelles textures utiliser pour la barre de progression. Utilisez les boutons de défilement en avant ou arrière pour naviguer entre les choix possibles. La texture sur la gauche correspond à la jauge, la texture sur la droite à l'arrière-plan de la jauge.",
		layprogtint = L"Vous pouvez ici colorer la barre de progression pour en modifier sa teinte. Vous pouvez également définir sa transparence. Vous pouvez voir l'aperçu de ces réglages sur la gauche ou sur la zone de glisser-déposer tout en haut.",
		layunusedbin = L"Cette zone contient les éléments qui ne sont actuellement pas compris dans le bloc. Vous pouvez glisser-déposer chacun d'eux dans la zone de bloc sur la gauche pour les y inclure. Les bulles d'aides permettent d'identifier chaque élément en les survolant.",
		layvis = L"Vous pouvez ici définir quand rendre visible la plupart des éléments.\
* Utilisez les boutons de défilement pour sélectionner l'élément à modifier.\
* Utilisez les cases à cocher pour définir les phases durant lesquelles l'élément ainsi sélectionné sera affiché.",
		setautoreap = L"Si vous avez une version à jour de Crafting Info Tooltip, vous pouvez utiliser la récolte automatique. Si activé, chaque fois que vous plantez ou récoltez une graine, MGRemix récoltera une plante pour chaque graine, dont vous êtes à court, d'un nombre que vous aurez spécifié ici.",
		setingred = L"Ici est déterminé à quel niveau les ingrédients doivent-ils être pour apparaître dans les menus contextuels",
		setlang = L"Vous pouvez ici spécifier la langue utilisée par l'addon.\
Par défaut c'est votre langue de jeu qui sera utilisée, si disponible, le cas échéant ce sera l'anglais.\
\
Les phrases qui n'ont pas été traduites apparaîtrons en anglais.\
Tout le monde peut contribuer à la traduction depuis http://war.curseforge.com/projects/mgremix/localization.",
		setmainwin = L"*Afficher la fenêtre* permet d'afficher la fenêtre principale.\
*Activer le bouton d'affichage* ajoute un icone sur votre interface permettant d'afficher ou masquer la fenêtre principale.\
*Activer l'effet d'avertissement* permet de faire varier la couleur d'arrière-plan de la fenêtre principale pour attirer votre attention une fois le processus de récolte accompli. La couleur utilisée peut être configurée en dessous.",
		setsound = L"Vous pouvez activer ou désactiver tous les sons. Vous pouvez aussi choisir quels sons utiliser. Appuyez sur Tester pour jouer le son sélectionné. Tous les sons ne sont pas audibles.",
	},
	messages = {
		help0 = L"/mg - Ouvre le panneau de réglages",
		help1 = L"Miracle Grow Remix par Irinia de Volkmar v{1}",
		help10 = L"/mg soundnum [nombre] - Change le son joué lors des changements de phase de culture",
		help11 = L"/mg soundnum2 [nombre] - Change le son joué lorsque la culture est terminée",
		help12 = L"/mg playsound [nombre] - Joue le son indiqué (pour trouver celui qui vous convient)",
		help13 = L"/mg reserve [nombre] - Essaie de préserver automatiquement un stock de sûreté du nombre de graines indiqué",
		help2 = L"Commandes slash (utilisez /mg, /mgremix ou /MiracleGrow2)",
		help3 = L"/mg help - Affiche cette liste de commandes",
		help4 = L"/mg sound [on/off] - Active ou désactive les sons",
		help5 = L"/mg throb [on/off] - Active ou désactive l'effet de clignotement",
		help6 = L"/mg minlvl [nombre] - Détermine le niveau minimum des composants à afficher",
		help7 = L"/mg maxlvl [nombre] - Détermine le niveau maximum des composants à afficher (indiquez 0 pour utiliser votre niveau d'artisanat)",
		help8 = L"/mg show - Affiche la fenêtre",
		help9 = L"/mg hide - Masque la fenêtre",
		maxlvl = L"MGRemix n'affichera maintenant plus que les objets de niveau inférieur ou égal à {1}",
		maxlvldef = L"MGRemix n'affichera maintenant plus que les objets de niveau inférieur ou égal à votre niveau d'artisanat",
		maxlvlerr = L"maxlvl doit être compris entre 0 et 200",
		minlvl = L"MGRemix n'affichera maintenant plus que les objets de niveau supérieur ou égal à {1}",
		minlvlerr = L"minlvl doit être compris entre 1 et 200",
		reserve = L"MGRemix fera de son mieux pour préserver {1} graines pour tout ce que vous ferez pousser",
		reserveoff = L"MGRemix ne convertira pas automatiquement les plantes",
		soundoff = L"Les sons de MGRemix sont maintenant désactivés",
		soundon = L"Les sons de MGRemix sont maintenant activés",
		throboff = L"L'effet d'avertissement de MGRemix est maintenant désactivé",
		throbon = L"L'effet d'avertissement de MGRemix est maintenant activé",
	},
	rant = {
		cit1 = L"Crafting Info Tooltip fournit à Miracle Grow Remix des informations sur les types de plantes que donneront les graines, informations qui seront alors affichées dans le menu contextuel. De plus, avec les informations données par Crafting Info Tooltip, Miracle Grow Remix peut automatiquement préserver un stock de graines par mesure de sûreté.",
		citnoinstall = L"Crafting Info Tooltip n'est pas installé.",
		citupdate = L"Crafting Info Tooltip n'est pas mis à jour.",
		libs1 = L"Sans LibSlash, vous ne pourrez pas utiliser les commandes vous permettant de configurer Miracle Grow Remix.",
		libsnoinstall = L"LibSlash n'est pas installé.",
		namecit = L"Crafting Info Tooltip",
		namelibslash = L"LibSlash",
		needupdate = L"{1} n'est pas à jour",
		noinstall = L"{1} n'est pas installé",
		rantpostfix = L"Vous ne serez pas averti de nouveau avant la prochaine version",
		rantprefix = L"Miracle Grow Remix a détécté qu'une ou plusieurs de ses dépendances sont manquantes ou périmées :",
		uptodate = L"{1] v{2} détecté et en service",
		version = L"La version {1} ou supérieure est requise.",
	},
	tooltips = {
		addnut = L"Ajouter nutriment",
		addseed = L"Ajouter graine",
		addsoil = L"Ajouter terreau",
		addwater = L"Ajouter eau",
		harvest = L"Récolter",
		hrepeat = L"Récolter puis répéter",
		nothing = L"<vide>",
		plotnum = L"Nombre de blocs",
		Repeat = L"Répéter",
		repeatnut = L"Nutriment",
		repeatseed = L"Graine",
		repeatsoil = L"Terreau",
		repeattitle = L"Répéter la dernière récolte",
		repeatwater = L"Eau",
		timeplot = L"Temps de récolte restant",
		timestage = L"Temps de phase restant",
		togglewindow = L"Afficher/Masquer Miracle Grow Remix",
	},
}
