HealGridSkin_WideMedium = {

	skin = {
		id = "WIDE_MEDIUM",
		name = L"Wide - Medium",
		author = "rmet0815",
		sortCriteria = "WIDE_20",
	},

	grid = {
		orientation = 'HORIZONTAL',
		growth = 'DOWN',
		unitFrame = {
			width = 200,
			height = 40,
			borderWidth = 2,
			borderHeight = 2,
			background = {
				color = "BLACK",
				texture = "WARTintSquare",
				style = "TILE",
			},
			careerLineIcon = {
				scale = 80,
				alpha = 50,
				position = 'LEFT',
				paddingX = "2",
				paddingY = "0",
				isVisible = true,
			},
			healthPointsBar = {
				anchor1 = { windowName="SELF", point="TOPLEFT", relativeTo="PARENT", relativePoint="TOPLEFT", offsetX="0", offsetY="0", },
				anchor2 = { windowName="SELF", point="BOTTOMRIGHT", relativeTo="PARENT", relativePoint="BOTTOMRIGHT", offsetX="0", offsetY="0", },
				growth = "LEFT_RIGHT",
				foreground = {
					isVisible = true,
					color = "GREEN",
					texture = "HalD",
					style = "FILL",
				},
				background = {
					isVisible = false,
					color = "BLACK",
					texture = "WARTintSquare",
					style = "TILE",
				},
				isToggleable = false,
				isVisible = true,
			},
			actionPointsBar = {
				anchor1 = { windowName="SELF", point="BOTTOMRIGHT", relativeTo="PARENT", relativePoint="TOPLEFT", offsetX="-20%", offsetY="-10%", },
				anchor2 = { windowName="SELF", point="BOTTOMRIGHT", relativeTo="PARENT", relativePoint="BOTTOMRIGHT", offsetX="0", offsetY="0", },
				growth = "RIGHT_LEFT",
				foreground = {
					isVisible = true,
					color = "ROYAL_BLUE",
					texture = "BantoBar",
					style = "FILL",
				},
				background = {
					isVisible = false,
					color = "LIGHT_SLATE_GRAY",
					texture = "WARTintSquare",
					style = "TILE",
				},
				isToggleable = true,
				isVisible = false,
			},
			moraleLevelBar = {
				anchor1 = { windowName="SELF", point="BOTTOMRIGHT", relativeTo="PARENT", relativePoint="TOPLEFT", offsetX="-20%", offsetY="-20%", },
				anchor2 = { windowName="SELF", point="BOTTOMRIGHT", relativeTo="PARENT", relativePoint="BOTTOMRIGHT", offsetX="0", offsetY="-10%", },
				growth = "RIGHT_LEFT",
				foreground = {
					isVisible = true,
					color = "GOLD",
					texture = "BantoBar",	
					style = "FILL",
				},
				background = {
					isVisible = false,
					color = "BLACK",
					texture = "WARTintSquare",
					style = "TILE",
				},
				isToggleable = true,
				isVisible = false,
			},
			spellTrack1 = {
				font = "font_clear_small",
				position = 'TOPLEFT',
				maxWidth = 100,
			},
			spellTrack2 = {
				font = "font_clear_small",
				position = 'BOTTOMLEFT',
				maxWidth = 100,
			},
			labelTopLeft = {
				label = L"",
				font = "font_clear_small",
				paddingX = "0",
				paddingY = "0",
				color = 'WHITE',
				isTargeted = false,
				inAvatarGroup = false,
			},
			labelTop = {
				label = L"[level] [career]",
				font = "font_clear_small_bold",
				paddingX = "0",
				paddingY = "2",
				color = 'WHITE',
				isTargeted = true,
				inAvatarGroup = true,
			},
			labelTopRight = {
				label = L"",
				font = "font_clear_small",
				paddingX = "0",
				paddingY = "0",
				color = 'WHITE',
				isTargeted = false,
				inAvatarGroup = false,
			},
			labelLeft = {
				label = L"",
				font = "font_clear_small",
				paddingX = "0",
				paddingY = "0",
				color = 'WHITE',
				isTargeted = false,
				inAvatarGroup = false,
			},
			labelCenter = {
				label = L"",
				font = "font_clear_small",
				paddingX = "0",
				paddingY = "0",
				color = 'WHITE',
				isTargeted = false,
				inAvatarGroup = false,
			},
			labelRight = {
				label = L"[hpperc]",
				font = "font_clear_large_bold",
				paddingX = "-2",
				paddingY = "0",
				color = 'WHITE',
				isTargeted = false,
				inAvatarGroup = false,
			},
			labelBottomLeft = {
				label = L"",
				font = "font_clear_small",
				paddingX = "0",
				paddingY = "0",
				color = 'WHITE',
				isTargeted = false,
				inAvatarGroup = true,
			},
			labelBottom = {
				label = L"[name]",
				font = "font_clear_medium_bold",
				paddingX = "0",
				paddingY = "0",
				color = 'CLASSCOLOR',
				isTargeted = false,
				inAvatarGroup = false,
			},
			labelBottomRight = {
				label = L"",
				font = "font_clear_small",
				paddingX = "0",
				paddingY = "0",
				color = 'WHITE',
				isTargeted = false,
				inAvatarGroup = false,
			},
		},
		petFrame = {
			height = 20,
			borderWidth = 2,
			borderHeight = 2,
			labelCenter = {
				font = "font_clear_small_bold",
			},
		},
	},

};

HealGridSkin.RegisterSkin( HealGridSkin_WideMedium, 'MELLI_MEDIUM' );
