Enemy.MaxGroups = 10
	
Enemy.Fonts =
{
	"font_chat_text",
	"font_alert_outline_giant",
	"font_alert_outline_gigantic",
	"font_alert_outline_half_giant",
	"font_alert_outline_half_gigantic",
	"font_alert_outline_half_huge",
	"font_alert_outline_half_large",
	"font_alert_outline_half_medium",
	"font_alert_outline_half_small",
	"font_alert_outline_half_tiny",
	"font_alert_outline_huge",
	"font_alert_outline_large",
	"font_alert_outline_medium",
	"font_alert_outline_small",
	"font_alert_outline_tiny",
	"font_chat_text",
	"font_chat_text_bold",
	"font_chat_text_no_outline",
	"font_clear_default",
	"font_clear_large",
	"font_clear_large_bold",
	"font_clear_medium",
	"font_clear_medium_bold",
	"font_clear_small",
	"font_clear_small_bold",
	"font_clear_tiny",
	"font_default_heading",
	"font_default_medium_heading",
	"font_default_sub_heading",
	"font_default_sub_heading_no_outline",
	"font_default_text",
	"font_default_text_giant",
	"font_default_text_gigantic",
	"font_default_text_huge",
	"font_default_text_large",
	"font_default_text_no_outline",
	"font_default_text_small",
	"font_default_war_heading",
	"font_guild_MP_R_17",
	"font_guild_MP_R_19",
	"font_guild_MP_R_23",
	"font_heading_20pt_no_shadow",
	"font_heading_22pt_no_shadow",
	"font_heading_big_noshadow",
	"font_heading_default",
	"font_heading_default_no_shadow",
	"font_heading_huge",
	"font_heading_huge_no_shadow",
	"font_heading_huge_noshadow",
	"font_heading_large",
	"font_heading_large_noshadow",
	"font_heading_medium",
	"font_heading_medium_noshadow",
	"font_heading_rank",
	"font_heading_small_no_shadow",
	"font_heading_target_mouseover_name",
	"font_heading_tiny_no_shadow",
	"font_heading_unitframe_con",
	"font_heading_unitframe_large_name",
	"font_heading_zone_name_no_shadow",
	"font_journal_body",
	"font_journal_body_large",
	"font_journal_heading",
	"font_journal_heading_smaller",
	"font_journal_small_heading",
	"font_journal_sub_heading",
	"font_journal_text",
	"font_journal_text_huge",
	"font_journal_text_italic",
	"font_journal_text_large"
}

Enemy.TextAligns =
{
	"left",
	"leftcenter",
	"bottomleft",
	"top",
	"center",
	"bottom",
	"right",
	"rightcenter",
	"bottomright"
}
	
Enemy.Anchors =
{
	"topleft",
	"left",
	"bottomleft",
	"top",
	"center",
	"bottom",
	"topright",
	"right",
	"bottomright"
}
	
Enemy.ScenarioCareerIdToLine =
{
	[20] = GameData.CareerLine.IRON_BREAKER,
	[100] = GameData.CareerLine.SWORDMASTER,
	[64] = GameData.CareerLine.CHOSEN,
	[24] = GameData.CareerLine.BLACK_ORC,
	[60] = GameData.CareerLine.WITCH_HUNTER,
	[102] = GameData.CareerLine.WHITE_LION,
	[65] = GameData.CareerLine.MARAUDER,
	[105] = GameData.CareerLine.WITCH_ELF,
	[62] = GameData.CareerLine.BRIGHT_WIZARD,
	[67] = GameData.CareerLine.MAGUS,
	[107] = GameData.CareerLine.SORCERER,
	[23] = GameData.CareerLine.ENGINEER,
	[101] = GameData.CareerLine.SHADOW_WARRIOR,
	[27] = GameData.CareerLine.SQUIG_HERDER,
	[63] = GameData.CareerLine.WARRIOR_PRIEST,
	[106] = GameData.CareerLine.DISCIPLE,
	[103] = GameData.CareerLine.ARCHMAGE,
	[26] = GameData.CareerLine.SHAMAN,
	[22] = GameData.CareerLine.RUNE_PRIEST,
	[66] = GameData.CareerLine.ZEALOT,
	[104] = GameData.CareerLine.BLACKGUARD,
	[61] = GameData.CareerLine.KNIGHT,
	[25] = GameData.CareerLine.CHOPPA,
	[21] = GameData.CareerLine.SLAYER
}