local Enemy = Enemy

Enemy.ScenarioInfoTestData =
{
	scenarioData =
	{
		maxTimer = 10000,
		startingScenario = 2108,
		destructionPoints = 123,
		id = 0,
		queuedWithGroup = false,
		destructionRace = 0,
		orderRace = 0,
		activeQueue = 0,
		orderPoints = 123,
		mode = 3,
		timeLeft = 1000,
		pointMax = 0,
	},
	
	players = 
	{
		{
			deaths = 0,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 0,
			name = L"Aaa",
			renown = 0,
			db = 0,
			archetype2 = 19,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 20,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 202,
			name = L"Bbb",
			renown = 9122,
			db = 5,
			archetype2 = 19,
			exp = 4809,
			damage = 103813,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 16,
			level = 40,
			kills = 0,
			name = L"Ccc",
			renown = 0,
			db = 0,
			archetype2 = 6,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 2,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 14,
			level = 40,
			kills = 9,
			name = L"Ddd",
			renown = 1260,
			db = 0,
			archetype2 = 5,
			exp = 175,
			damage = 2809,
		},
		
		{
			deaths = 2,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 8,
			name = L"Eee",
			renown = 339,
			db = 0,
			archetype2 = 19,
			exp = 586,
			damage = 9257,
		},
		
		{
			deaths = 2,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 24,
			level = 40,
			kills = 4,
			name = L"Fff",
			renown = 12,
			db = 1,
			archetype2 = 1,
			exp = 31,
			damage = 49116,
		},
		
		{
			deaths = 17,
			archetype = "mdps",
			realm = 1,
			healing = 1800,
			soloKills = 0,
			career = 19,
			level = 40,
			kills = 179,
			name = L"Ggg",
			renown = 6633,
			db = 2,
			archetype2 = 10,
			exp = 4584,
			damage = 135688,
		},
		
		{
			deaths = 11,
			archetype = "healers",
			realm = 1,
			healing = 935772,
			soloKills = 0,
			career = 3,
			level = 40,
			kills = 214,
			name = L"Hhh",
			renown = 8039,
			db = 0,
			archetype2 = 18,
			exp = 5158,
			damage = 5345,
		},
		
		{
			deaths = 8,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 1,
			level = 40,
			kills = 204,
			name = L"Iii",
			renown = 9618,
			db = 1,
			archetype2 = 22,
			exp = 5014,
			damage = 57746,
		},
		
		{
			deaths = 1,
			archetype = "healers",
			realm = 1,
			healing = 23845,
			soloKills = 0,
			career = 20,
			level = 40,
			kills = 1,
			name = L"Jjj",
			renown = 170,
			db = 0,
			archetype2 = 17,
			exp = 31,
			damage = 0,
		},
		
		{
			deaths = 3,
			archetype = "healers",
			realm = 2,
			healing = 1559968,
			soloKills = 0,
			career = 15,
			level = 40,
			kills = 275,
			name = L"Kkk",
			renown = 36466,
			db = 0,
			archetype2 = 15,
			exp = 30001,
			damage = 8073,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 5,
			level = 40,
			kills = 0,
			name = L"Lll",
			renown = 0,
			db = 0,
			archetype2 = 21,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 4,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 24,
			level = 40,
			kills = 269,
			name = L"Mmm",
			renown = 28388,
			db = 112,
			archetype2 = 1,
			exp = 29894,
			damage = 2578879,
		},
		
		{
			deaths = 4,
			archetype = "healers",
			realm = 2,
			healing = 980792,
			soloKills = 0,
			career = 23,
			level = 40,
			kills = 237,
			name = L"Nnn",
			renown = 14809,
			db = 1,
			archetype2 = 13,
			exp = 8563,
			damage = 17800,
		},
		
		{
			deaths = 0,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 6,
			level = 40,
			kills = 0,
			name = L"Ooo",
			renown = 0,
			db = 0,
			archetype2 = 2,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 4,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 269,
			name = L"Ppp",
			renown = 32809,
			db = 16,
			archetype2 = 19,
			exp = 33995,
			damage = 325920,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 23,
			level = 40,
			kills = 0,
			name = L"Qqq",
			renown = 0,
			db = 0,
			archetype2 = 13,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 36,
			kills = 0,
			name = L"Rrr",
			renown = 0,
			db = 0,
			archetype2 = 7,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 8,
			level = 40,
			kills = 0,
			name = L"Sss",
			renown = 0,
			db = 0,
			archetype2 = 3,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 1,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 5,
			level = 40,
			kills = 6,
			name = L"Ttt",
			renown = 2412,
			db = 0,
			archetype2 = 21,
			exp = 144,
			damage = 5128,
		},
		
		{
			deaths = 0,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 22,
			level = 40,
			kills = 0,
			name = L"Uuu",
			renown = 0,
			db = 0,
			archetype2 = 4,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 13,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 8,
			level = 36,
			kills = 218,
			name = L"Vvv",
			renown = 13286,
			db = 2,
			archetype2 = 3,
			exp = 4697,
			damage = 196644,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 18,
			level = 40,
			kills = 0,
			name = L"Www",
			renown = 0,
			db = 0,
			archetype2 = 12,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 5,
			archetype = "healers",
			realm = 1,
			healing = 1136281,
			soloKills = 0,
			career = 12,
			level = 40,
			kills = 248,
			name = L"Xxx",
			renown = 14913,
			db = 0,
			archetype2 = 16,
			exp = 14922,
			damage = 6287,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 20,
			level = 40,
			kills = 0,
			name = L"Yyy",
			renown = 0,
			db = 0,
			archetype2 = 17,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 11,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 10,
			level = 40,
			kills = 239,
			name = L"Zzz",
			renown = 16227,
			db = 7,
			archetype2 = 24,
			exp = 18363,
			damage = 174110,
		},
		
		{
			deaths = 15,
			archetype = "mdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 9,
			level = 40,
			kills = 212,
			name = L"Aaa2",
			renown = 15950,
			db = 11,
			archetype2 = 9,
			exp = 20326,
			damage = 439348,
		},
		
		{
			deaths = 8,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 40,
			kills = 243,
			name = L"Bbb2",
			renown = 20646,
			db = 99,
			archetype2 = 7,
			exp = 29143,
			damage = 1654743,
		},
		
		{
			deaths = 6,
			archetype = "healers",
			realm = 1,
			healing = 991749,
			soloKills = 0,
			career = 12,
			level = 40,
			kills = 244,
			name = L"Ccc2",
			renown = 22604,
			db = 0,
			archetype2 = 16,
			exp = 29143,
			damage = 44240,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 0,
			name = L"Ddd2",
			renown = 0,
			db = 0,
			archetype2 = 19,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 5,
			archetype = "healers",
			realm = 2,
			healing = 1028049,
			soloKills = 0,
			career = 7,
			level = 40,
			kills = 249,
			name = L"Eee2",
			renown = 17298,
			db = 1,
			archetype2 = 14,
			exp = 8830,
			damage = 13449,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 21,
			level = 40,
			kills = 0,
			name = L"Fff2",
			renown = 0,
			db = 0,
			archetype2 = 20,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 13,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 40,
			kills = 222,
			name = L"Ggg2",
			renown = 9387,
			db = 19,
			archetype2 = 7,
			exp = 8905,
			damage = 476009,
		},
		
		{
			deaths = 13,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 17,
			level = 40,
			kills = 233,
			name = L"Hhh2",
			renown = 9971,
			db = 8,
			archetype2 = 23,
			exp = 8034,
			damage = 241135,
		},
		
		{
			deaths = 27,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 40,
			kills = 195,
			name = L"Iii2",
			renown = 12777,
			db = 37,
			archetype2 = 7,
			exp = 11078,
			damage = 1150463,
		},
		
		{
			deaths = 6,
			archetype = "healers",
			realm = 1,
			healing = 816173,
			soloKills = 0,
			career = 20,
			level = 40,
			kills = 238,
			name = L"Jjj2",
			renown = 17361,
			db = 1,
			archetype2 = 17,
			exp = 22327,
			damage = 52555,
		},
		
		{
			deaths = 0,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 14,
			level = 40,
			kills = 0,
			name = L"Kkk2",
			renown = 0,
			db = 0,
			archetype2 = 5,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 23,
			level = 40,
			kills = 0,
			name = L"Lll2",
			renown = 0,
			db = 0,
			archetype2 = 13,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 3,
			archetype = "mdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 2,
			level = 40,
			kills = 98,
			name = L"Mmm2",
			renown = 3888,
			db = 0,
			archetype2 = 8,
			exp = 4201,
			damage = 28093,
		},
		
		{
			deaths = 17,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 4,
			level = 40,
			kills = 230,
			name = L"Nnn2",
			renown = 10539,
			db = 11,
			archetype2 = 11,
			exp = 8137,
			damage = 491012,
		},
		
		{
			deaths = 6,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 8,
			level = 40,
			kills = 282,
			name = L"Ooo2",
			renown = 17642,
			db = 32,
			archetype2 = 3,
			exp = 11991,
			damage = 753492,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 24,
			level = 40,
			kills = 0,
			name = L"Ppp2",
			renown = 0,
			db = 0,
			archetype2 = 1,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 14,
			level = 40,
			kills = 0,
			name = L"Qqq2",
			renown = 0,
			db = 0,
			archetype2 = 5,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 8,
			level = 40,
			kills = 0,
			name = L"Rrr2",
			renown = 0,
			db = 0,
			archetype2 = 3,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 5,
			archetype = "healers",
			realm = 2,
			healing = 914296,
			soloKills = 0,
			career = 23,
			level = 40,
			kills = 239,
			name = L"Sss2",
			renown = 18635,
			db = 2,
			archetype2 = 13,
			exp = 17392,
			damage = 25067,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 24,
			level = 40,
			kills = 0,
			name = L"Ttt2",
			renown = 0,
			db = 0,
			archetype2 = 1,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 31,
			kills = 0,
			name = L"Uuu2",
			renown = 0,
			db = 0,
			archetype2 = 7,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 21,
			level = 40,
			kills = 0,
			name = L"Vvv2",
			renown = 0,
			db = 0,
			archetype2 = 20,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 12,
			archetype = "healers",
			realm = 1,
			healing = 838873,
			soloKills = 0,
			career = 12,
			level = 40,
			kills = 242,
			name = L"Www2",
			renown = 12175,
			db = 2,
			archetype2 = 16,
			exp = 11479,
			damage = 43449,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 23,
			level = 40,
			kills = 0,
			name = L"Xxx2",
			renown = 0,
			db = 0,
			archetype2 = 13,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 15,
			level = 40,
			kills = 0,
			name = L"Yyy2",
			renown = 0,
			db = 0,
			archetype2 = 15,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 0,
			name = L"Zzz2",
			renown = 0,
			db = 0,
			archetype2 = 19,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 29,
			archetype = "mdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 19,
			level = 35,
			kills = 133,
			name = L"Aaa3",
			renown = 11425,
			db = 5,
			archetype2 = 10,
			exp = 7185,
			damage = 105758,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 40,
			kills = 0,
			name = L"Bbb3",
			renown = 0,
			db = 0,
			archetype2 = 7,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 12,
			level = 40,
			kills = 0,
			name = L"Ccc3",
			renown = 0,
			db = 0,
			archetype2 = 16,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 9,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 1,
			career = 24,
			level = 40,
			kills = 250,
			name = L"Ddd3",
			renown = 20723,
			db = 43,
			archetype2 = 1,
			exp = 14846,
			damage = 1022092,
		},
		
		{
			deaths = 3,
			archetype = "mdps",
			realm = 2,
			healing = 2717,
			soloKills = 0,
			career = 14,
			level = 40,
			kills = 14,
			name = L"Eee3",
			renown = 602,
			db = 0,
			archetype2 = 5,
			exp = 369,
			damage = 31148,
		},
		
		{
			deaths = 0,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 22,
			level = 40,
			kills = 0,
			name = L"Fff3",
			renown = 0,
			db = 0,
			archetype2 = 4,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 12,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 17,
			level = 40,
			kills = 92,
			name = L"Ggg3",
			renown = 3163,
			db = 9,
			archetype2 = 23,
			exp = 3096,
			damage = 202589,
		},
		
		{
			deaths = 7,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 1,
			level = 40,
			kills = 89,
			name = L"Hhh3",
			renown = 3899,
			db = 3,
			archetype2 = 22,
			exp = 1041,
			damage = 84413,
		},
		
		{
			deaths = 5,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 40,
			kills = 95,
			name = L"Iii3",
			renown = 3158,
			db = 1,
			archetype2 = 7,
			exp = 1032,
			damage = 123762,
		},
		
		{
			deaths = 10,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 1,
			career = 22,
			level = 31,
			kills = 145,
			name = L"Jjj3",
			renown = 13445,
			db = 11,
			archetype2 = 4,
			exp = 6621,
			damage = 117865,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 1,
			level = 40,
			kills = 0,
			name = L"Kkk3",
			renown = 0,
			db = 0,
			archetype2 = 22,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 14,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 240,
			name = L"Lll3",
			renown = 24667,
			db = 4,
			archetype2 = 19,
			exp = 12419,
			damage = 170736,
		},
		
		{
			deaths = 7,
			archetype = "tanks",
			realm = 2,
			healing = 516,
			soloKills = 0,
			career = 21,
			level = 40,
			kills = 267,
			name = L"Mmm3",
			renown = 37618,
			db = 10,
			archetype2 = 20,
			exp = 28971,
			damage = 280114,
		},
		
		{
			deaths = 20,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 1,
			career = 6,
			level = 40,
			kills = 207,
			name = L"Nnn3",
			renown = 20736,
			db = 11,
			archetype2 = 2,
			exp = 11082,
			damage = 111782,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 0,
			name = L"Ooo3",
			renown = 0,
			db = 0,
			archetype2 = 19,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 12,
			level = 40,
			kills = 0,
			name = L"Ppp3",
			renown = 0,
			db = 0,
			archetype2 = 16,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 12,
			level = 40,
			kills = 0,
			name = L"Qqq3",
			renown = 0,
			db = 0,
			archetype2 = 16,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 9,
			archetype = "tanks",
			realm = 1,
			healing = 18588,
			soloKills = 0,
			career = 10,
			level = 40,
			kills = 225,
			name = L"Rrr3",
			renown = 19248,
			db = 2,
			archetype2 = 24,
			exp = 23934,
			damage = 183452,
		},
		
		{
			deaths = 0,
			archetype = "mdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 2,
			level = 40,
			kills = 0,
			name = L"Sss3",
			renown = 0,
			db = 0,
			archetype2 = 8,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 19,
			archetype = "mdps",
			realm = 2,
			healing = 239,
			soloKills = 0,
			career = 14,
			level = 40,
			kills = 233,
			name = L"Ttt3",
			renown = 17552,
			db = 10,
			archetype2 = 5,
			exp = 8173,
			damage = 218135,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 10,
			level = 40,
			kills = 0,
			name = L"Uuu3",
			renown = 0,
			db = 0,
			archetype2 = 24,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 22,
			archetype = "tanks",
			realm = 2,
			healing = 29760,
			soloKills = 0,
			career = 5,
			level = 40,
			kills = 241,
			name = L"Vvv3",
			renown = 16430,
			db = 7,
			archetype2 = 21,
			exp = 8319,
			damage = 115678,
		},
		
		{
			deaths = 3,
			archetype = "healers",
			realm = 2,
			healing = 1383076,
			soloKills = 0,
			career = 15,
			level = 40,
			kills = 276,
			name = L"Www3",
			renown = 38914,
			db = 0,
			archetype2 = 15,
			exp = 30001,
			damage = 598,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 16,
			level = 40,
			kills = 11,
			name = L"Xxx3",
			renown = 2914,
			db = 0,
			archetype2 = 6,
			exp = 806,
			damage = 25208,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 8,
			level = 35,
			kills = 0,
			name = L"Yyy3",
			renown = 0,
			db = 0,
			archetype2 = 3,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 1,
			level = 40,
			kills = 0,
			name = L"Zzz3",
			renown = 0,
			db = 0,
			archetype2 = 22,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 15,
			level = 40,
			kills = 0,
			name = L"Aaa4",
			renown = 0,
			db = 0,
			archetype2 = 15,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 6,
			archetype = "healers",
			realm = 1,
			healing = 604928,
			soloKills = 0,
			career = 3,
			level = 40,
			kills = 229,
			name = L"Bbb4",
			renown = 16575,
			db = 0,
			archetype2 = 18,
			exp = 15417,
			damage = 364,
		},
		
		{
			deaths = 12,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 40,
			kills = 228,
			name = L"Ccc4",
			renown = 15300,
			db = 30,
			archetype2 = 7,
			exp = 15613,
			damage = 1019512,
		},
		
		{
			deaths = 0,
			archetype = "tanks",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 1,
			level = 40,
			kills = 0,
			name = L"Ddd4",
			renown = 0,
			db = 0,
			archetype2 = 22,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 5,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 24,
			level = 40,
			kills = 117,
			name = L"Eee4",
			renown = 7053,
			db = 18,
			archetype2 = 1,
			exp = 5502,
			damage = 239823,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 40,
			kills = 0,
			name = L"Fff4",
			renown = 0,
			db = 0,
			archetype2 = 7,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 1,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 8,
			level = 40,
			kills = 72,
			name = L"Ggg4",
			renown = 3323,
			db = 3,
			archetype2 = 3,
			exp = 1769,
			damage = 107549,
		},
		
		{
			deaths = 4,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 8,
			level = 40,
			kills = 244,
			name = L"Hhh4",
			renown = 14490,
			db = 18,
			archetype2 = 3,
			exp = 6713,
			damage = 363318,
		},
		
		{
			deaths = 16,
			archetype = "tanks",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 13,
			level = 40,
			kills = 194,
			name = L"Iii4",
			renown = 11842,
			db = 3,
			archetype2 = 19,
			exp = 4647,
			damage = 139502,
		},
		
		{
			deaths = 12,
			archetype = "tanks",
			realm = 1,
			healing = 71,
			soloKills = 0,
			career = 17,
			level = 40,
			kills = 101,
			name = L"Jjj4",
			renown = 4970,
			db = 5,
			archetype2 = 23,
			exp = 2028,
			damage = 87621,
		},
		
		{
			deaths = 0,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 6,
			level = 40,
			kills = 0,
			name = L"Kkk4",
			renown = 0,
			db = 0,
			archetype2 = 2,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 8,
			archetype = "rdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 24,
			level = 40,
			kills = 268,
			name = L"Lll4",
			renown = 37669,
			db = 29,
			archetype2 = 1,
			exp = 28686,
			damage = 714068,
		},
		
		{
			deaths = 22,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 22,
			level = 40,
			kills = 200,
			name = L"Mmm4",
			renown = 17888,
			db = 7,
			archetype2 = 4,
			exp = 7045,
			damage = 162159,
		},
		
		{
			deaths = 11,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 11,
			level = 40,
			kills = 108,
			name = L"Nnn4",
			renown = 5041,
			db = 10,
			archetype2 = 7,
			exp = 3788,
			damage = 230424,
		},
		
		{
			deaths = 0,
			archetype = "healers",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 23,
			level = 37,
			kills = 0,
			name = L"Ooo4",
			renown = 0,
			db = 0,
			archetype2 = 13,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 11,
			archetype = "tanks",
			realm = 2,
			healing = 1680,
			soloKills = 0,
			career = 5,
			level = 40,
			kills = 239,
			name = L"Ppp4",
			renown = 20747,
			db = 4,
			archetype2 = 21,
			exp = 8352,
			damage = 65205,
		},
		
		{
			deaths = 0,
			archetype = "rdps",
			realm = 1,
			healing = 0,
			soloKills = 0,
			career = 18,
			level = 36,
			kills = 0,
			name = L"Qqq4",
			renown = 0,
			db = 0,
			archetype2 = 12,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 0,
			archetype = "mdps",
			realm = 2,
			healing = 0,
			soloKills = 0,
			career = 6,
			level = 40,
			kills = 0,
			name = L"Rrr4",
			renown = 0,
			db = 0,
			archetype2 = 2,
			exp = 0,
			damage = 0,
		},
		
		{
			deaths = 9,
			archetype = "healers",
			realm = 1,
			healing = 659251,
			soloKills = 0,
			career = 3,
			level = 40,
			kills = 240,
			name = L"Sss4",
			renown = 25810,
			db = 2,
			archetype2 = 18,
			exp = 21725,
			damage = 34306,
		},
	}
}

Enemy.ScenarioInfoTestData_old =
{
	scenarioData = 
	{
		maxTimer = 0,
		startingScenario = 0,
		destructionPoints = 0,
		id = 0,
		queuedWithGroup = false,
		timeLeft = 0,
		pointMax = 0,
		activeQueue = 0,
		mode = 3,
		orderPoints = 0,
		orderRace = 0,
		destructionRace = 0,
	},
	
	players =
	{
		{
			rank = 8,
			deaths = 0,
			renownbonus = 0,
			renown = 13,
			isplayer = false,
			--damagedealt = 3826,
			damagedealt = 1980000,
			healingdealt = 0,
			solokills = 0,
			name = L"Rorung^M",
			careerId = 27,
			experience = 105,
			career = L"Squig Herder^m",
			groupkills = 2,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 8,
			deaths = 1,
			renownbonus = 0,
			renown = 0,
			isplayer = false,
			--damagedealt = 114,
			damagedealt = 170000,
			healingdealt = 0,
			solokills = 0,
			name = L"Getfat^M",
			careerId = 27,
			experience = 0,
			career = L"Squig Herder^m",
			groupkills = 0,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 8,
			deaths = 1,
			renownbonus = 0,
			renown = 0,
			isplayer = false,
			damagedealt = 2073,
			healingdealt = 0,
			solokills = 0,
			name = L"Fergrohir^M",
			careerId = 101,
			experience = 0,
			career = L"Shadow Warrior^m",
			groupkills = 0,
			deathblows = 0,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 4,
			deaths = 1,
			renownbonus = 0,
			renown = 1,
			isplayer = false,
			damagedealt = 1776,
			healingdealt = 0,
			solokills = 0,
			name = L"Drajz^M",
			careerId = 64,
			experience = 0,
			career = L"Chosen^m",
			groupkills = 1,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 1,
			deaths = 0,
			renownbonus = 0,
			renown = 0,
			isplayer = true,
			damagedealt = 0,
			healingdealt = 0,
			solokills = 0,
			name = L"Addontest^M",
			careerId = 25,
			experience = 0,
			career = L"Choppa^m",
			groupkills = 0,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 10,
			deaths = 0,
			renownbonus = 0,
			renown = 58,
			isplayer = false,
			damagedealt = 4642,
			healingdealt = 0,
			solokills = 0,
			name = L"Lokrak^M",
			careerId = 21,
			experience = 935,
			career = L"Slayer^m",
			groupkills = 9,
			deathblows = 1,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 10,
			deaths = 0,
			renownbonus = 0,
			renown = 58,
			isplayer = false,
			damagedealt = 2547,
			healingdealt = 6261,
			solokills = 0,
			name = L"Techlisa^F",
			careerId = 103,
			experience = 935,
			career = L"Archmage^f",
			groupkills = 9,
			deathblows = 0,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 5,
			deaths = 1,
			renownbonus = 0,
			renown = 0,
			isplayer = false,
			damagedealt = 1497,
			healingdealt = 0,
			solokills = 0,
			name = L"Ruggrat^M",
			careerId = 27,
			experience = 0,
			career = L"Squig Herder^m",
			groupkills = 0,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 8,
			deaths = 1,
			renownbonus = 0,
			renown = 34,
			isplayer = false,
			damagedealt = 4479,
			healingdealt = 0,
			solokills = 0,
			name = L"Koromen^M",
			careerId = 27,
			experience = 307,
			career = L"Squig Herder^m",
			groupkills = 2,
			deathblows = 1,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 7,
			deaths = 0,
			renownbonus = 0,
			renown = 23,
			isplayer = false,
			damagedealt = 2870,
			healingdealt = 0,
			solokills = 0,
			name = L"Tankshrek^M",
			careerId = 23,
			experience = 248,
			career = L"Engineer^m",
			groupkills = 8,
			deathblows = 2,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 9,
			deaths = 1,
			renownbonus = 0,
			renown = 61,
			isplayer = false,
			damagedealt = 0,
			healingdealt = 7038,
			solokills = 0,
			name = L"Xevalenia^F",
			careerId = 103,
			experience = 872,
			career = L"Archmage^f",
			groupkills = 9,
			deathblows = 0,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 3,
			deaths = 1,
			renownbonus = 0,
			renown = 45,
			isplayer = false,
			damagedealt = 2195,
			healingdealt = 0,
			solokills = 0,
			name = L"Kilathaz^M",
			careerId = 27,
			experience = 189,
			career = L"Squig Herder^m",
			groupkills = 2,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 8,
			deaths = 0,
			renownbonus = 0,
			renown = 34,
			isplayer = false,
			damagedealt = 3439,
			healingdealt = 0,
			solokills = 0,
			name = L"Chudobludce^F",
			careerId = 67,
			experience = 307,
			career = L"Magus^f",
			groupkills = 2,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 4,
			deaths = 0,
			renownbonus = 0,
			renown = 28,
			isplayer = false,
			damagedealt = 2017,
			healingdealt = 3223,
			solokills = 0,
			name = L"Moonwisper^F",
			careerId = 103,
			experience = 216,
			career = L"Archmage^f",
			groupkills = 9,
			deathblows = 0,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 6,
			deaths = 1,
			renownbonus = 0,
			renown = 15,
			isplayer = false,
			damagedealt = 1944,
			healingdealt = 0,
			solokills = 0,
			name = L"Eskol^M",
			careerId = 67,
			experience = 88,
			career = L"Magus^m",
			groupkills = 2,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 9,
			deaths = 1,
			renownbonus = 0,
			renown = 0,
			isplayer = false,
			damagedealt = 2010,
			healingdealt = 0,
			solokills = 0,
			name = L"Caemfinerlel^F",
			careerId = 107,
			experience = 0,
			career = L"Sorceress^f",
			groupkills = 0,
			deathblows = 1,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 5,
			deaths = 0,
			renownbonus = 0,
			renown = 76,
			isplayer = false,
			damagedealt = 1680,
			healingdealt = 0,
			solokills = 0,
			name = L"Lamechantante^M",
			careerId = 101,
			experience = 623,
			career = L"Shadow Warrior^m",
			groupkills = 9,
			deathblows = 3,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 4,
			deaths = 0,
			renownbonus = 0,
			renown = 81,
			isplayer = false,
			damagedealt = 3105,
			healingdealt = 0,
			solokills = 0,
			name = L"Wesemir^M",
			careerId = 61,
			experience = 558,
			career = L"Knight of the Blazing Sun^m",
			groupkills = 9,
			deathblows = 1,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 4,
			deaths = 1,
			renownbonus = 0,
			renown = 20,
			isplayer = false,
			damagedealt = 296,
			healingdealt = 2411,
			solokills = 0,
			name = L"Gamwstauros^M",
			careerId = 106,
			experience = 111,
			career = L"Disciple of Khaine^m",
			groupkills = 1,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 3,
			deaths = 1,
			renownbonus = 0,
			renown = 0,
			isplayer = false,
			damagedealt = 1861,
			healingdealt = 0,
			solokills = 0,
			name = L"Pruttprutt^M",
			careerId = 27,
			experience = 0,
			career = L"Squig Herder^m",
			groupkills = 0,
			deathblows = 0,
			experiencebonus = 0,
			realm = 2,
		},
		
		{
			rank = 2,
			deaths = 0,
			renownbonus = 0,
			renown = 27,
			isplayer = false,
			damagedealt = 2060,
			healingdealt = 0,
			solokills = 0,
			name = L"Valt^M",
			careerId = 23,
			experience = 145,
			career = L"Engineer^m",
			groupkills = 8,
			deathblows = 3,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 2,
			deaths = 0,
			renownbonus = 0,
			renown = 27,
			isplayer = false,
			damagedealt = 98,
			healingdealt = 2418,
			solokills = 0,
			name = L"Scull^F",
			careerId = 63,
			experience = 145,
			career = L"Warrior Priest^f",
			groupkills = 8,
			deathblows = 0,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 2,
			deaths = 0,
			renownbonus = 0,
			renown = 30,
			isplayer = false,
			damagedealt = 2335,
			healingdealt = 0,
			solokills = 0,
			name = L"Arenter^F",
			careerId = 102,
			experience = 168,
			career = L"White Lion^f",
			groupkills = 9,
			deathblows = 1,
			experiencebonus = 0,
			realm = 1,
		},
		
		{
			rank = 1,
			deaths = 0,
			renownbonus = 0,
			renown = 30,
			isplayer = false,
			damagedealt = 1337,
			healingdealt = 0,
			solokills = 0,
			name = L"Lolemon^M",
			careerId = 62,
			experience = 148,
			career = L"Bright Wizard^m",
			groupkills = 9,
			deathblows = 1,
			experiencebonus = 0,
			realm = 1,
		}
	}
}